/* Biome registry: cubiomes BiomeID enum value -> 1.18+ resource id + display name.
 * Colors come from cubiomes' default (Amidst-derived) colormap at runtime. */

export interface BiomeDef {
  id: number;
  name: string;
}

const B: Record<number, string> = {
  0: 'Ocean',
  1: 'Plains',
  2: 'Desert',
  3: 'Windswept Hills',
  4: 'Forest',
  5: 'Taiga',
  6: 'Swamp',
  7: 'River',
  8: 'Nether Wastes',
  9: 'The End',
  10: 'Frozen Ocean',
  11: 'Frozen River',
  12: 'Snowy Plains',
  13: 'Snowy Mountains',
  14: 'Mushroom Fields',
  15: 'Mushroom Field Shore',
  16: 'Beach',
  17: 'Desert Hills',
  18: 'Wooded Hills',
  19: 'Taiga Hills',
  20: 'Mountain Edge',
  21: 'Jungle',
  22: 'Jungle Hills',
  23: 'Sparse Jungle',
  24: 'Deep Ocean',
  25: 'Stony Shore',
  26: 'Snowy Beach',
  27: 'Birch Forest',
  28: 'Birch Forest Hills',
  29: 'Dark Forest',
  30: 'Snowy Taiga',
  31: 'Snowy Taiga Hills',
  32: 'Old Growth Pine Taiga',
  33: 'Old Growth Spruce Taiga Hills',
  34: 'Windswept Forest',
  35: 'Savanna',
  36: 'Savanna Plateau',
  37: 'Badlands',
  38: 'Wooded Badlands',
  39: 'Badlands Plateau',
  40: 'Small End Islands',
  41: 'End Midlands',
  42: 'End Highlands',
  43: 'End Barrens',
  44: 'Warm Ocean',
  45: 'Lukewarm Ocean',
  46: 'Cold Ocean',
  47: 'Deep Warm Ocean',
  48: 'Deep Lukewarm Ocean',
  49: 'Deep Cold Ocean',
  50: 'Deep Frozen Ocean',
  127: 'The Void',
  128: 'Sunflower Plains',
  129: 'Desert Lakes',
  130: 'Gravelly Mountains',
  131: 'Flower Forest',
  132: 'Taiga Mountains',
  133: 'Swamp Hills',
  134: 'Ice Spikes',
  135: 'Modified Jungle',
  136: 'Modified Jungle Edge',
  137: 'Tall Birch Forest',
  138: 'Tall Birch Hills',
  139: 'Dark Forest Hills',
  140: 'Snowy Taiga Mountains',
  141: 'Giant Spruce Taiga',
  142: 'Giant Spruce Taiga Hills',
  143: 'Modified Gravelly Mountains',
  144: 'Shattered Savanna',
  145: 'Shattered Savanna Plateau',
  146: 'Eroded Badlands',
  147: 'Modified Wooded Badlands Plateau',
  148: 'Modified Badlands Plateau',
  168: 'Bamboo Jungle',
  169: 'Bamboo Jungle Hills',
  170: 'Soul Sand Valley',
  171: 'Crimson Forest',
  172: 'Warped Forest',
  173: 'Basalt Deltas',
  174: 'Dripstone Caves',
  175: 'Lush Caves',
  177: 'Meadow',
  178: 'Grove',
  179: 'Snowy Slopes',
  180: 'Jagged Peaks',
  181: 'Frozen Peaks',
  182: 'Stony Peaks',
  183: 'Deep Dark',
  184: 'Mangrove Swamp',
  185: 'Cherry Grove',
  186: 'Pale Garden',
};

export function biomeName(id: number): string {
  return B[id] ?? `Biome ${id}`;
}